[package]
name = "bioparser"
version = "0.1.0"
edition = "2024"

[dependencies]
noodles = { version = "0.61.0", features = ["bam", "sam", "vcf"] }
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"

